### ISSUE TITLE
Files not found

### ISSUE THREAD

**Issue by afern247** [RiuHDuo/PrettyAxis#1]
Hi, I'm getting the following error as I downloaded the Demo app

![image](https://user-images.githubusercontent.com/34192856/157986874-7a12550e-4da3-4c5e-8f80-04164cf15455.png)

**Comment by RiuHDuo** [comment]
I am sorry， i forgot push project file. Please fetch new code.

**Comment by afern247** [comment]
It looks pretty good, is there a possibility to make it interactive?

For example the line graph to be able to tap on it and see the stock prices by day

**Comment by RiuHDuo** [comment]
> It looks pretty good, is there a possibility to make it interactive?
> 
> For example the line graph to be able to tap on it and see the stock prices by day

You want it like this?
![1](https://user-images.githubusercontent.com/830134/160962112-50cd8d83-97d7-4036-9231-aee6b50c22bf.gif)
![1](https://user-images.githubusercontent.com/830134/160962981-111fd972-cc0a-4b54-9ed9-1706c1605210.gif)

**Comment by afern247** [comment]
Yes that would be good
